---
exchanges:
  - name: "uniswap"
    node_urls:
      - "wss://ethereum-mainnet.core.chainstack.com/ws/5f899c2bcc20c7d53a77f049887752ca"
      - "wss://ethereum.publicnode.com"
    pools:
      - address: "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"
        base: "WETH"
        quote: "USDC"
        base_decimal: 6
        quote_decimal: 18
        invert_price: true
      - address: "0xcbcdf9626bc03e24f779434178a73a0b4bad62ed"
        base: "WBTC"
        quote: "WETH"
        base_decimal: 8
        quote_decimal: 18
        invert_price: false
      - address: "0x840deeef2f115cf50da625f7368c24af6fe74410"
        base: "CBETH"
        quote: "WETH"
        base_decimal: 18
        quote_decimal: 18
        invert_price: false
      - address: "0xa4e0faa58465a2d369aa21b3e42d43374c6f9613"
        base: "RETH"
        quote: "WETH"
        base_decimal: 18
        quote_decimal: 18
        invert_price: false
      - address: "0xd340b57aacdd10f96fc1cf10e15921936f41e29c"
        base: "WSTETH"
        quote: "WETH"
        base_decimal: 18
        quote_decimal: 18
        invert_price: false
      - address: "0xeed4603bc333ef406e5eb691ba66798d5c857d8b"
        base: "SFRXETH"
        quote: "WETH"
        base_decimal: 18
        quote_decimal: 18
        invert_price: false
      - address: "0xa6cc3c2531fdaa6ae1a3ca84c2855806728693e8"
        base: "LINK"
        quote: "WETH"
        base_decimal: 18
        quote_decimal: 18
        invert_price: false
      - address: "0x63818bbdd21e69be108a23ac1e84cbf66399bd7d"
        base: "STETH"
        quote: "WETH"
        base_decimal: 18
        quote_decimal: 18
        invert_price: false
  - name: "camelot"
    node_urls:
      - "wss://arbitrum-one-rpc.publicnode.com"
    pools:
      - address: "0x8Bf9C3975172c57E37b3D1c1348e9b5280FB3BaA"
        base: "MILKTIA"
        quote: "TIA"
        base_decimal: 6
        quote_decimal: 6
        invert_price: false
  - name: "balancer"
    node_urls:
      - "wss://mainnet.infura.io/ws/v3/6849a09aeeb044b592d46bcdce07ccef"
    pools:
      - address: "0x4216d5900a6109bba48418b5e2AB6cc4e61Cf477"
        base: "AMPHRETH"
        quote: "ETH"
        base_address: "0x5fD13359Ba15A84B76f7F87568309040176167cd"
        quote_addresses:
          - "0x7a4EffD87C2f3C55CA251080b1343b605f327E3a"
          - "0x84631c0d0081FDe56DeB72F6DE77abBbF6A9f93a"
          - "0xBEEF69Ac7870777598A04B2bd4771c71212E6aBc"
          - "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0"
        base_decimal: 18
        quote_decimal: 18
        invert_price: false
      - address: "0x4216d5900a6109bba48418b5e2AB6cc4e61Cf477"
        base: "RSTETH"
        quote: "ETH"
        base_address: "0x7a4EffD87C2f3C55CA251080b1343b605f327E3a"
        quote_addresses:
          - "0x5fD13359Ba15A84B76f7F87568309040176167cd"
          - "0x84631c0d0081FDe56DeB72F6DE77abBbF6A9f93a"
          - "0xBEEF69Ac7870777598A04B2bd4771c71212E6aBc"
          - "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0"
        base_decimal: 18
        quote_decimal: 18
        invert_price: false
      - address: "0x4216d5900a6109bba48418b5e2AB6cc4e61Cf477"
        base: "RE7LRT"
        quote: "ETH"
        base_address: "0x84631c0d0081FDe56DeB72F6DE77abBbF6A9f93a"
        quote_addresses:
          - "0x5fD13359Ba15A84B76f7F87568309040176167cd"
          - "0x7a4EffD87C2f3C55CA251080b1343b605f327E3a"
          - "0xBEEF69Ac7870777598A04B2bd4771c71212E6aBc"
          - "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0"
        base_decimal: 18
        quote_decimal: 18
        invert_price: false
      - address: "0x4216d5900a6109bba48418b5e2AB6cc4e61Cf477"
        base: "STEAKLRT"
        quote: "ETH"
        base_address: "0xBEEF69Ac7870777598A04B2bd4771c71212E6aBc"
        quote_addresses:
          - "0x5fD13359Ba15A84B76f7F87568309040176167cd"
          - "0x7a4EffD87C2f3C55CA251080b1343b605f327E3a"
          - "0x84631c0d0081FDe56DeB72F6DE77abBbF6A9f93a"
          - "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0"
        base_decimal: 18
        quote_decimal: 18
        invert_price: false

server:
  listen_addr: "0.0.0.0:5005"
  write_timeout: "20s"
  read_timeout: "20s"
  broadcast_interval: "5s"
