---
node_url: "wss://ethereum.publicnode.com"
server:
  listen_addr: "0.0.0.0:5005"
  write_timeout: "20s"
  read_timeout: "20s"
  broadcast_interval: "5s"
pools:
  - address: "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"
    base: "WETH"
    quote: "USDC"
    base_decimal: 6
    quote_decimal: 18
    invert_price: true
  - address: "0xcbcdf9626bc03e24f779434178a73a0b4bad62ed"
    base: "WBTC"
    quote: "WETH"
    base_decimal: 8
    quote_decimal: 18
    invert_price: false
  - address: "0x840deeef2f115cf50da625f7368c24af6fe74410"
    base: "CBETH"
    quote: "WETH"
    base_decimal: 18
    quote_decimal: 18
    invert_price: false
  - address: "0xa4e0faa58465a2d369aa21b3e42d43374c6f9613"
    base: "RETH"
    quote: "WETH"
    base_decimal: 18
    quote_decimal: 18
    invert_price: false
  - address: "0xd340b57aacdd10f96fc1cf10e15921936f41e29c"
    base: "WSTETH"
    quote: "WETH"
    base_decimal: 18
    quote_decimal: 18
    invert_price: false
  - address: "0x8a15b2dc9c4f295dcebb0e7887dd25980088fdcb"
    base: "SFRXETH"
    quote: "WETH"
    base_decimal: 18
    quote_decimal: 18
    invert_price: false
  - address: "0xa6cc3c2531fdaa6ae1a3ca84c2855806728693e8"
    base: "LINK"
    quote: "WETH"
    base_decimal: 18
    quote_decimal: 18
    invert_price: false
