---
node_urls: [
  "ABBITRUM WEBSOCKET URL HERE",
]
server:
  listen_addr: "0.0.0.0:5005"
  write_timeout: "20s"
  read_timeout: "20s"
  broadcast_interval: "5s"
pools:
  - address: "0x8Bf9C3975172c57E37b3D1c1348e9b5280FB3BaA"
    base: "MILKTIA"
    quote: "TIA"
    base_decimal: 6
    quote_decimal: 6
    invert_price: false
