---
node_url: "wss://ethereum.publicnode.com"
pools:
  - exchange_pair: "WETH/USDC"
    address: "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"
    base_decimal: 18
    quote_decimal: 6
    invert_price: true

  - exchange_pair: "WBTC/WETH"
    address: "0x2f5e87c9312fa29aed5c179e456625d79015299c"
    base_decimal: 6
    quote_decimal: 8
    invert_price: false
