name: Build
on:
  pull_request:
  push:
    branches:
      - main

# This workflow makes amd64 and arm64 binaries for macOS and Linux.
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [darwin, linux]
    name: ethereum-api ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Configure Git for GitHub Actions
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Set GOPRIVATE for private repositories
        run: echo "export GOPRIVATE=github.com/ojo-network" >> $GITHUB_ENV
      - name: Authenticate with GitHub Package Registry
        run: echo "//${{ github.token }}:x-oauth-basic@npm.pkg.github.com/:_authToken=${{ github.token }}" > ~/.npmrc

      - name: Compile
        run: |
          go mod download
          cd cmd
          go build .
      - uses: actions/upload-artifact@v3
        with:
          name: ethereum-api ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/ethereum-api
