name: Lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/ojo-network/indexer
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.53
          args: --timeout 5m

  super-linter:
    name: Run super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`.
          fetch-depth: 0
      - name: Run super-linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
